from numpy import *
from Lineal import *


a=array([[4,2,2],[2,5,4],[5,1,3]], float)
b=array([[18.0],[27.30],[16.20]], float)
x=array([[1],[1],[1]], float)
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()
print(gausseidel(a,b,x))
print()